# Generated by Django 5.2.4 on 2025-07-09 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empleados", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="empleado",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="empleados/fotos/"),
        ),
        migrations.CreateModel(
            name="BitacoraEmpleado",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "accion",
                    models.CharField(choices=[("CREACIÓN", "Creación"), ("EDICIÓN", "Edición"), ("ELIMINACIÓN", "Eliminación")], max_length=20),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("detalles", models.TextField(blank=True)),
                ("empleado", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="empleados.empleado")),
                ("usuario", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
